Console.WriteLine("Mug mug mug");
Console.WriteLine("Coffee mug");
Console.WriteLine("Gonna clear away the haze");
Console.WriteLine("Liquid proof");
Console.WriteLine("That I can win this race");
Console.WriteLine("Coffee mug");
Console.WriteLine("The grip that keeps me tall");
Console.WriteLine("My inter-link");
Console.WriteLine("Keeps me questing all");
Console.WriteLine("I don't need no booze or drugs");
Console.WriteLine("I just chug-a-lug-o my coffee mug");
Console.WriteLine("And I don't need your kiss and hug");
Console.WriteLine("I just chug-a-lug-o my coffee mug");
Console.WriteLine("They haven't banned");
Console.WriteLine("My liquid drug of choice");
Console.WriteLine("There's too many hooked");
Console.WriteLine("And they've got too much voice");
Console.WriteLine("So for the moment");
Console.WriteLine("We're all pretty good to go");
Console.WriteLine("With 98 cups");
Console.WriteLine("With 98 more to go");
Console.WriteLine("I don't need no booze or drugs");
Console.WriteLine("I just chug-a-lug-o my coffee mug");
Console.WriteLine("And I don't need your kiss and hug");
Console.WriteLine("I just chug-a-lug-o my coffee mug");
Console.WriteLine("Here a bean, there a bean");
Console.WriteLine("Everywhere a mean mean");
Console.WriteLine("Bean chug - a - lug - o - my");
Console.WriteLine("Coffee - mug, mug, mug, mug");
